# Welcome to Jekyll!

# Website settings
title: an
description: CrazyAndy's blog,use Jekyll and github pages.
keywords: CrazyAndy,blog,Jekyll,github,gh-pages
baseurl:  
url: http://CrazyAndy.github.io
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: an  # Be used at blog posts' author.
  github_username: CrazyAndy  # Leave blank if you don't have now
  email: auden.sh@163.com  # Leave blank if you don't have now
  avatar: /static/assets/img/landing/avatar.jpg
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: 俺的博客。

#categories


# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-paginate